I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 4268, in script
    menu:
  File "game/script.rpy", line 4275, in <module>
    "Bite it." if Vine3_NormalBite == True:
NameError: name 'Vine3_NormalBite' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 4268, in script
    menu:
  File "renpy/ast.py", line 1633, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "renpy/exports.py", line 995, in menu
    condition = renpy.python.py_eval(condition)
  File "renpy/python.py", line 2142, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2135, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 4275, in <module>
    "Bite it." if Vine3_NormalBite == True:
NameError: name 'Vine3_NormalBite' is not defined

